### PR TITLE
[TASK] Code cleanup and add gitattributes to exclude files for archive

### PR DESCRIPTION
**Pull request by simonschaufi**

### CODE REVIEW

**Comment by mficzel** [comment]
I kind of like the cleanup (once tests are green) but am not sure about the .gitattributes What exactly do they optimize. 

Background: On the long run this repo will be moved to the neos-development-collection it is developed seperately to be able to release faster than neos if needed while its new.

**Comment by simonschaufi** [comment]
I did everything by hand with a Phpstorm Plugin: https://plugins.jetbrains.com/plugin/7622-php-inspections-ea-extended-/ which i can highly recommend.

Regarding the .gitattributes: This makes sure that when you require the package via composer, only the necessary files are downloaded (since you don't need tests in your production system).

**Comment by simonschaufi** [comment]
@mficzel ping

**Comment by mficzel** [comment]
Thank you for the reminder. I still like the cleanup but not the .gitattributes.

Also some of the adjustments seem to be a bit strict. As the current state breaks the Neos Login. The problem is that with all changes in one pr this is really hard to digest if i want to relflect on all of them  and since there is proof that the automagic did at least one unsafe change change i would rather have this as multiple prs.

A separate pr that adds .gitattributes to the neos and flow-development collection would make sense and allow to discuss this with the whole team.

**Comment by simonschaufi** [comment]
@mficzel I removed the gitattributes for now to keep on moving forward.

**Comment by simonschaufi** [comment]
@mficzel what is wrong with this pr? I don't feel motivated do contribute again as it takes a huge amount of time and then the code lies around for a long time and in the end it doesn't get merged. 💩

**Comment by mficzel** [comment]
Feel free to contact me via Neos Slack if you need advice how to split this up.

**Pull request closed without merging**
